name: Ilaria
options:
  bundleIdPrefix: app.gsuss
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: es
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  Ilaria:
    type: application
    platform: iOS
    sources:
      - Ilaria
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.gsuss.ilaria
        INFOPLIST_FILE: Ilaria/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 25
        MARKETING_VERSION: "1.5.9"
        GENERATE_INFOPLIST_FILE: false
