"""Short acknowledgment phrases for zero-latency Piper cache."""

from __future__ import annotations

# Keep under ~140 chars so they hit the TTS cache path.
COMMON_PHRASES: tuple[str, ...] = (
    "Listo.",
    "Hecho.",
    "Entendido.",
    "Por supuesto.",
    "Dale.",
    "Ya.",
    "OK.",
    "Okey.",
    "Perfecto.",
    "Claro.",
    "Hecho, jefe.",
    "Listo, jefe.",
    "Entendido, jefe.",
    "Volumen ajustado.",
    "Volumen al veinte.",
    "Volumen al treinta.",
    "Volumen al cuarenta.",
    "Volumen al cincuenta.",
    "Volumen al sesenta.",
    "Volumen al setenta.",
    "Volumen al ochenta.",
    "Volumen al cien.",
    "Volumen al 30%.",
    "Volumen al 50%.",
    "Volumen al 70%.",
    "Mute.",
    "Silenciado.",
    "Siguiente.",
    "Anterior.",
    "Pausa.",
    "Play.",
    "Abriendo.",
    "Abierto.",
    "Captura lista.",
    "Anotado.",
    "Asentado en el diario.",
    "Timer listo.",
    "Recordatorio guardado.",
    "Buscando.",
    "Un segundo.",
    "Ya vuelvo.",
    "No encontré nada.",
    "No hay nada para deshacer.",
    "Deshecho.",
    "Volumen restaurado.",
    "Portapapeles actualizado.",
    "Sin resultados.",
    "Hecho en el celular.",
    "Abriendo Spotify.",
    "Abriendo Chrome.",
    "Abriendo el mapa.",
    "Listo, abrí brave.",
    "Listo, abrí youtube.",
    "Listo, abrí spotify.",
    "Listo, abrí notepad.",
    "Listo, abrí excel.",
    "Listo, abrí calculadora.",
    "Listo, abrí discord.",
    "Te escucho.",
    "Te escucho…",
    "No te escuché bien.",
    "No te escuché bien. Decilo otra vez después de llamarme.",
    "Decime.",
    "¿En qué te ayudo?",
    "Estoy online.",
    "Todo bien.",
    "Permiso denegado.",
    "Eso es de la PC.",
)
